language: python

cache:
  - pip

matrix:
  include:
    - os: linux
      python: "3.5.1"

install:
  - pip install -U pip wheel
  - pip install hacking autopep8

script:
  - flake8
  - autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
  - test ! -s check_autopep8

sudo: false

